#
# Client: Antoine Solutions
# Project: The Essentialist
#

services:
  node:
    command: bash
    depends_on:
      - mailcatcher
    environment:
      # node
      NODE_ENV:
      NODE_PORT:
      # jwilder/nginx_proxy
      VIRTUAL_HOST: ${COMPOSE_PROJECT_NAME}.${DOMAIN}
      VIRTUAL_PORT: ${NODE_PORT}
    hostname: node.${COMPOSE_PROJECT_NAME}
    expose:
      - ${NODE_PORT}
    image: node:latest
    restart: unless-stopped
    stdin_open: true
    tty: true
    user: node
    volumes:
      - ./1_The_Physical/Level_1_Stateless_Guess_Point/2_Manage_Complexity/3_2_Boolean_Calculator:/home/node/app
    working_dir: /home/node/app

  mailcatcher:
    environment:
      # jwilder/nginx_proxy
      VIRTUAL_HOST: mailcatcher-${COMPOSE_PROJECT_NAME}.${DOMAIN}
      VIRTUAL_PORT: 1080
    hostname: mailcatcher.${COMPOSE_PROJECT_NAME}
    image: schickling/mailcatcher
    networks:
      - default
    restart: unless-stopped
